config/routes.rb
Fratapps::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tasks
  
  
  match '/about', :to => 'about#index'
  match '/contact', :to => 'contact#index'
  match '/help', :to => 'help#index'
  match '/tour', :to => 'tour#index'
  match '/users', :to => 'users#index'
  match '/groups', :to => 'groups#index'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/dashboard', :to => 'dashboard#index'
  match '/dashboard/admin', :to => 'dashboard#index'
  match '/dashboard/user', :to => 'dashboard#index'
  match '/dashboard/submit_for_approval', :to => 'dashboard#submit_for_approval'
  match '/dashboard/take', :to => 'dashboard#take'
  match '/tasks/new', :to => 'tasks#new'
  match '/tasks/finished/:id', :to => 'tasks#finished'
  match '/tasks/unfinished/:id', :to => 'tasks#unfinished'
  match '/dashboard/leaderboard', :to => 'dashboard#leaderboard'
  
  

 	root :to => "home#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_filter :authenticate
	
	def index
		# Set the locals to be displayed in the tables
		# Open tasks for the group
		@open_task_instances = []
		all_open_task_instances = TaskInstance.find(:all, :conditions => "status = 'open'")
		for n in 0...all_open_task_instances.length
			task_user = all_open_task_instances[n].task.created_by_id
			user = User.find_by_id(task_user)
			if current_user.group.eql? user.group
				@open_task_instances.push all_open_task_instances[n]
			end
		end	
		
		# Tasks belonging to the logged in user
		@user_task_instances = current_user.task_instances
		
		# The top ten users for the leaderboard
		@leaderboard_users = current_user.group.users.all(:limit => 10)
		@leaderboard_users.sort!{|a,b| b.points.points <=> a.points.points}
		#@leaderboard_users = User.find(:all,
		#  :order => "total_points desc, name",
		#  :limit => 10)
		
		# Pending tasks for admins
		if current_user.admin? or current_user.super_admin?
			@pending_task_instances = []
			all_pending_task_instances = TaskInstance.find(:all, :conditions => "status = 'pending'")
			all_pending_task_instances.each do |ti|
				task_user = ti.task.created_by_id
				user = User.find_by_id(task_user)
				if current_user.group.eql? user.group
					@pending_task_instances.push ti
				end
			end
		end
		
		
		# TODO:Overdue tasks for admins
		@overdue_task_instances = [] if current_user.admin? or current_user.super_admin?
  
		if current_user.admin?
			render 'admin'
		else
			render 'user'
		end
	end
	
	
	def leaderboard
		# Set the local for the table
		# All users sorted by points then name
		@leaderboard_users = current_user.group.users.all(:limit => 10)
		@leaderboard_users.sort!{|a,b| b.points.points <=> a.points.points}
	end
	
	def take
		# Find the task to take
		task_instance = TaskInstance.find(params[:id])
		
		# Redirect with a message if the task isn't open anymore
		unless task_instance.status == 'open'
		  flash[:notice] = 'Unable to take that task (someone may have beat you to it).'
		  redirect_to :action => 'index'
		  return
		end
		
		# Take the task, updating the necessary attributes
		task_instance.user_id = current_user.id
		task_instance.status = 'taken'
		task_instance.taken_on = Time.now
		
		# Save the task and redirect with a message
		if task_instance.save
		  flash[:notice] = 'Task taken successfully.'
		  redirect_to :action => 'index'
		else
		  flash[:notice] = 'Unable to take that task.'
		  redirect_to :action => 'index'
		end
	end
	
	begin
	def abandon
		# Find the task to abandon
		task_instance = TaskInstance.find(params[:id])
		
		# Redirect with a message if the active user doesn't own that task
		unless task_instance.user_id == current_user.id
		  flash[:notice] = "Unable to abandon that task."
		  redirect_to :action => 'index'
		  return
		end
		
		# Abandon the task, updating the necessary attributes
		task_instance.user_id = nil
		task_instance.status = 'open'
		task_instance.taken_on = nil
		
		# Save the task and redirect with a message
		if task_instance.save
		  flash[:notice] = 'Task abandoned.'
		  redirect_to :action => 'index'
		else
		  flash[:notice] = 'Unable to abandon that task.'
		  redirect_to :action => 'index'
		end
	end
	end
	
	def submit_for_approval
		# Find the task to submit
		task_instance = TaskInstance.find(params[:id])
		
		# Check that the user owns the task
		unless task_instance.user_id == current_user.id
		  flash[:notice] = 'Unable to update task.'
		  redirect_to :action => 'index'
		end
		
		# Change the status to pending
		task_instance.status = 'pending'
		
		# Save the task and redirect with a message
		if task_instance.save
		  flash[:notice] = 'Task submitted for approval.'
		  redirect_to :action => 'index'
		else
		  flash[:notice] = 'Unable to update task.'
		  redirect_to :action => 'index'
		end
	end
	
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_task_instance.html.erb
<tr class="<%= cycle('list-line-odd', 'list-line-even') %>">
    <% if fields.include?("name") %>
    <td>
        <%=h task_instance.task.name %>
    </td>
    <% end %>
    <% if fields.include?("description") %>
    <td>
        <%=h task_instance.task.description %>
    </td>
    <% end %>
    <% if fields.include?("created_by_id") %>
    <td>
        <%=h User.find(task_instance.task.created_by_id).name %>
    </td>
    <% end %>
	<% if fields.include?("user") %>
	<td>
		<%=h User.find(task_instance.user_id).name %>
	</td>
	<% end %>
    <% if fields.include?("created_at") %>
    <td>
        <%=h task_instance.task.created_at.strftime("%m-%d-%y") %>
    </td>
    <% end %>
    <% if fields.include?("taken_on") %>
    <td>
        <%=h task_instance.taken_on.strftime("%m-%d-%y") %>
    </td>
    <% end %>
    <% if fields.include?("complete_on") %>
    <td>
        <%=h task_instance.complete_on.strftime("%m-%d-%y") if task_instance.complete_on %>
    </td>
    <% end %>
    <% if fields.include?("status") %>
    <td>
    	<% if fields.include?("replace_status_with_submit_for_approval") and task_instance.status == 'taken' %>
			<%= link_to "Submit for Approval", :action => 'submit_for_approval', :id => task_instance %>
		<% elsif fields.include?("replace_status_with_submit_for_approval") and task_instance.status == 'unfinished' %>
			<%= link_to "Unfinished, Resubmit for Approval", :action => 'submit_for_approval', :id => task_instance %>	
		<% else %>
        	<%=h task_instance.status %>
		<% end %>
    </td>
    <% end %>
    <% if fields.include?("points") %>
    <td class="points">
        <%=h task_instance.task.points %>
    </td>
    <% end %>
    <% if fields.include?("take_btn") %>
    <td>
        <%= link_to "Take", :action => "take", :id => task_instance %>
    </td>
    <% end %>
    <% if fields.include?("abandon_btn") && task_instance.status != 'finished' %>
    <td>
        <%= link_to "Abandon", :action => "abandon", :id => task_instance %>
    </td>
    <% end %>
	<% if fields.include?("finished_btn") %>
	<td>
		<%= link_to "Finished", :controller => "tasks", :method => "POST", :action => "finished", :id => task_instance.id %>
	</td>
	<% end %>
	<% if fields.include?("unfinished_btn") %>
	<td>
		<%= link_to "Unfinished", :controller => 'tasks', :method => "POST", :action => 'unfinished', :id => task_instance.id %>
	</td>
	<% end %>
</tr>

app/views/dashboard/_user.html.erb
<tr class="<%= cycle('list-line-odd', 'list-line-even') %>">
  <td><%= user.name %></td>
  <td><%= user.points.points %></td>
</tr>

app/views/dashboard/admin.html.erb
<div id="featured_wrapper_outside">
	<div id="content_wrapper">
		
		<div id="leaderboard">
			<h3>My Points: <%= current_user.points.points %></h3>
			<h2>Leaderboard</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Points</th>
				</tr>
			
			<%= render(:partial => "user", :collection => @leaderboard_users) %>
			</table>
			
			<%= link_to "Full Board", dashboard_leaderboard_path %>
		</div>
		
		<div id="yourTasks">
		<% if @user_task_instances.empty? %>
		    <h2>Your Tasks</h2>	
		    <div id="noTasks">
			<h3 class="middleText">You do not have any new tasks. Get to work!</h3>
		     </div>
	 	<% else %>	
			<% unless @user_task_instances.empty? %>
			<h2>Your Tasks</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Created by</th>
					<th>Taken on</th>
					<th>Complete on</th>
					<th>Status</th>
					<th>Points</th>
				</tr>
				
				<% fields = ["name", "description", "created_by_id", "taken_on", "complete_on",
						   "status", "points", "replace_status_with_submit_for_approval"] %>
				<%= render(:partial => "task_instance", :collection => @user_task_instances, :locals => { :fields => fields }) %>
			</table>
			<% end %>
		<% end %>			
		</div>

		<div id="availableTasks">  
		<% if @open_task_instances.empty? %>
			<h2>Available Tasks</h2>
			    <div id="noTasks">
				<h3 class="middleText">No tasks for members to take.

		                <% if current_user.admin? %>
			  		<%= link_to "Create New Task", tasks_new_path %>
			  	<% end %>
				</h3>
			     </div>
		<% else %>
			<% unless @open_task_instances.empty? %>
			<h2>Available Tasks</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Created By</th>
					<th>Created On</th>
					<th>Complete On</th>
					<th>Points</th>
					<th>Status</th>
				</tr>
			
				<% fields = ["name", "description", "created_by_id", "created_at", "complete_on", "points", "take_btn"] %> 
				<%= render(:partial => "task_instance", :collection => @open_task_instances, :locals => { :fields => fields }) %>
			</table>
			<% end %>
		  <% end %>
		  	<% if current_user.admin? %>
		  		<%= link_to "New Task", tasks_new_path %>
		  	<% end %>
		   			
		</div>

		<% if current_user.admin? or current_user.super_admin? %>
		<% if @pending_task_instances.empty? %>
			<div id="pendingTasks">
			    <h2>Pending Tasks</h2>
			    <div id="noTasks">
				<h3 class="middleText">No tasks to mark complete. Tell your members to do work!</h3>
			     </div>
		<% else %>
			<% unless @pending_task_instances.empty? %>
			<h2>Pending Tasks</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Created by</th>
					<th>User</th>
					<th>Taken on</th>
					<th>Complete on</th>
					<th>Points</th>
				</tr>
				<% fields = ["name", "description", "created_by_id", "user", "taken_on",
					   "complete_on", "points", "finished_btn", "unfinished_btn"] %>
				<%= render(:partial => "task_instance", :collection => @pending_task_instances,
					 :locals => { :fields => fields }) %>
			</table>
			<% end %>
		   <% end %>	
		</div>
				
		<% end %>			

	</div>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/dashboard/leaderboard.html.erb
<div id="featured_wrapper_outside">
	<div id="content_wrapper">
		<div>
			<h3>My Points: <%= current_user.points.points %></h3>
			<h2>Leaderboard</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Points</th>
				</tr>
		
				<%= render(:partial => "user", :collection => @leaderboard_users) %>
			</table>
		
			<%= link_to "Go Back", dashboard_path %>
		</div>			
	</div>
</div>


app/views/dashboard/user.html.erb
<div id="featured_wrapper_outside">
	<div id="content_wrapper">
		<div id="leaderboard">
			<h3>My Points: <%= current_user.points.points %></h3>
			<h2>Leaderboard</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Points</th>
				</tr>
			
			<%= render(:partial => "user", :collection => @leaderboard_users) %>
			</table>
			
			<%= link_to "Full Board", dashboard_leaderboard_path %>
		</div>
		  
		<div id="yourTasks">

			<% unless @user_task_instances.empty? %>
			<h2>Your Tasks</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Created by</th>
					<th>Taken on</th>
					<th>Complete on</th>
					<th>Status</th>
					<th>Points</th>
				</tr>
				
				<% fields = ["name", "description", "created_by_id", "taken_on", "complete_on",
						   "status", "points", "replace_status_with_submit_for_approval"] %>
				<%= render(:partial => "task_instance", :collection => @user_task_instances, :locals => { :fields => fields }) %>
			</table>
			<% end %>
		  
			<a href="">Propose Task</a>
		</div>

		<div id="availableTasks">  

			<% unless @open_task_instances.empty? %>
			<h2>Available Tasks</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Created By</th>
					<th>Points</th>
					<th>Complete on</th>
					<th>Status</th>
					<th>Created On</th>
				</tr>
			
				<% fields = ["name", "description", "created_by_id", "created_at", "complete_on", "points", "take_btn"] %> 
				<%= render(:partial => "task_instance", :collection => @open_task_instances, :locals => { :fields => fields }) %>
			</table>
			<% end %>
		  
		  	<% if current_user.admin? %>
		  		<%= link_to "View all tasks" %>
		  		<%= link_to "New Task", tasks_new_path %>
		  	<% end %>
		</div>

		<% if current_user.admin? or current_user.super_admin? %>
		<div id="pendingTasks">
			<% unless @pending_task_instances.empty? %>
			<h2>Pending Tasks</h2>
			<table>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Created by</th>
					<th>User</th>
					<th>Taken on</th>
					<th>Complete on</th>
					<th>Points</th>
				</tr>
				<% fields = ["name", "description", "created_by_id", "user", "taken_on",
					   "complete_on", "points", "finished_btn", "unfinished_btn"] %>
				<%= render(:partial => "task_instance", :collection => @pending_task_instances,
					 :locals => { :fields => fields }) %>
			</table>
			<% end %>
			<h2>No Pending Tasks</h2>
		</div>
			
		<div id="overdueTasks">
			<% if @overdue_task_instances.size > 0 %>
				<h2>Overdue Tasks</h2>	
			<% else %>
				<h2 style="text-decoration: line-through;">No Overdue Tasks</h2>
			<% end %>
		</div>
		<% end %>			

	</div>
</div>